Forum/Models/ErrorViewModel.cs
using System;

namespace Forum.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Forum/Models/PagingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Forum.Models
{
    public class PagingModel
    {
        public int PageNumber { get; set; }
        public int TotalPages { get; set; }

        public PagingModel(int count, int pageNumber, int pageSize)
        {
            PageNumber = pageNumber;
            TotalPages = (int)Math.Ceiling(count / (double)pageSize);
        }

        public bool HasPreviousPage => PageNumber > 1;

        public bool HasNextPage => PageNumber < TotalPages;

    }
    
    
}

Forum/Models/TopicCreateModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

namespace Forum.Models
{
    public class TopicCreateModel
    {
        [Required]
        [Display(Name = "Название темы")]
        public string Headline { get; set; }
        [Required]
        [Display(Name = "Содержание")]
        public string Content { get; set; }
    }
}

Forum/Models/TopicIndexModel.cs
using System.Collections.Generic;

namespace Forum.Models
{
    public class TopicIndexModel
    {
        public List<TopicModel> Topics { get; set; }
        public int? Page { get; set; }
        public PagingModel PagingModel { get; set; }
        
    }
}

Forum/Models/TopicModel.cs
using System.ComponentModel.DataAnnotations;

namespace Forum.Models
{
    public class TopicModel
    {
        public int Id { get; set; }

        [Display(Name = "Дата создания")]
        public string DateCreated { get; set; }

        [Display(Name = "Автор темы")]
        public string AuthorName { get; set; }

        [Display(Name = "Название темы")]
        public string Headline { get; set; }

        [Display(Name = "Содержание")]
        
        public string ContentPreview { get; set; }
    }
}

Forum/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Forum.Models;

namespace Forum.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Forum/Controllers/TopicController.cs
using System;
using System.Threading.Tasks;
using Forum.DAL.Entities;
using Forum.Models;
using Forum.Services.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Forum.Controllers
{
    public class TopicController : Controller
    {
        private readonly ITopicService _topicService;
        private readonly UserManager<User> _userManager;

        public TopicController(ITopicService topicService, UserManager<User> userManager)
        {
            _topicService = topicService;
            _userManager = userManager;
        }

        public IActionResult Index(TopicIndexModel model)
        {
            try
            {
                var topicModels = _topicService.GetAllTopics(model);
                model.Topics = topicModels;
                
                return View(model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]

        public async Task<IActionResult> CreateTopic(TopicCreateModel model)
        {
            try
            {
                User currentUser = await _userManager.GetUserAsync(User);
                _topicService.CreateTopic(model, currentUser.Id);

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }
    }

}

Forum/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Forum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Форум</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Форум любителей форумов</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная страница</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Topic" asp-action="Index">Темы</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Forum - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Forum/Views/Topic/Create.cshtml
@model Forum.Models.TopicCreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>TopicCreateModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateTopic"method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Headline" class="control-label"></label>
                <input asp-for="Headline" class="form-control" />
                <span asp-validation-for="Headline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Forum/Views/Topic/Index.cshtml
@model TopicIndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Все темы</h1>

<p>
    <a asp-action="Create">Новая тема</a>
</p>
<table class="table">
    
    <tbody>
    @foreach (var item in Model.Topics) 
    {
        <tr>
            
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AuthorName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Headline)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContentPreview)
            </td>
           
        </tr>
    }
    </tbody>
</table>
@if (Model.PagingModel.HasPreviousPage)
{
    @Html.ActionLink("<< Назад", "Index", "Topic",
        new TopicIndexModel()
        {
           
            Page = Model.Page - 1
        })
}

<b>@Model.Page</b>

@if (Model.PagingModel.HasNextPage)
{
    @Html.ActionLink("Вперед >>", "Index", "Topic",
        new TopicIndexModel()
        {
            Page = Model.Page + 1
        })
}